Repository hack4bengal/hack4bengal.github.io, pull requests merged in 2022-10, with the labels that each got.

#89 Added all partners in community partners page section
  community-partners.html
Labels: bug, hacktoberfest-accepted, 💻 aspect: code, 🛠 goal: fix, 🟧 priority: high, 🕹 aspect: interface, 🥗 status: ready for merge

#88 Changed Timeline Date Details
  index.html
Labels: good first issue, hacktoberfest-accepted, 🛠 goal: fix, 🟧 priority: high, 🕹 aspect: interface, 🥗 status: ready for merge

#92 updated contribution guide
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted, ✨ goal: improvement
